### ISSUE TITLE
[Bug] Mod does not load on 1.20.4 Neoforge

### ISSUE THREAD

**Issue by Saereth** [SuperMartijn642/FormationsNether#3]
**Version Info**
- Minecraft, 1.20.4
- Formations, formations-1.0.2-neoforge-mc1.20.4.jar
- Formations Nether, formationsnether-1.0.2.jar

**What mod loader are you using?**: Fabric/Forge/NeoForge/Quilt
NeoForge

**Description of the Bug**
Formations Nether and Overworld are both tagged neoforge on CF but they have internal depdencies on Forge still instead of Neoforge

`[25Apr2024 23:10:34.666] [main/ERROR] [net.neoforged.fml.loading.LanguageLoadingProvider/LOADING]: Missing language lowcodefml version [46,) wanted by formationsnether-1.0.2.jar, found 2.0`

**Comment by SuperMartijn642** [comment]
This was already fixed in an update last year. Updating to a newer version of Formations Nether should fix the issue.
