### ISSUE TITLE
[Question] Server-side only?

### ISSUE THREAD

**Issue by MJRamon** [SuperMartijn642/FormationsNether#4]
**Question**
On Modrinth page it is stated that mod is required on client: https://modrinth.com/mod/formations-nether

Why? What does it add except generation, that is done server-side only?

**Comment by SuperMartijn642** [comment]
Formations Nether is not required on the client. Where does it say so on the Modrinth page?

**Comment by MJRamon** [comment]
> Formations Nether is not required on the client. Where does it say so on the Modrinth page?

I provided the link.

Here are screenshots:

![screen](https://github.com/SuperMartijn642/FormationsNether/assets/2642227/ce300fe3-1e43-4cfa-b201-db2e610afe93)

![screen](https://github.com/SuperMartijn642/FormationsNether/assets/2642227/3244bdc4-e952-4a72-89cf-967f25e701c7)

**Comment by MJRamon** [comment]
Same thing with Formations (Structure Library), by the way

**Comment by SuperMartijn642** [comment]
Updated it now! Likely left over from when they weren't server-side only on Forge.
Thank you for reporting it!
